### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by pacharanero** [JoeriHermans/Tag-And-Warp#3]
Hi, not wanting to dissuade you from your project but just thought I'd mention that there are a number of simialr projects already doing what `warp` does:

For ZSH / oh-my-zsh: https://github.com/mfaerevaag/wd
For any shell: https://github.com/mfaerevaag/wd-c
For any shell: https://github.com/iridakos/goto

I can see why a number of people are working on a utility that does this, it's greatly useful. It should be part of the standard Unix tooling IMO :smile:

**Comment by JoeriHermans** [comment]
wd-c looks pretty well done imho.

I'm actually not "maintaining" this project anymore, I made this somewhere in 2016 if I recall correctly.
